// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFnHyym94pRVpCPdcYc0MRnTBVA-bwN0',
    appId: '1:199291967208:web:e5ba4f650a35958c151b5d',
    messagingSenderId: '199291967208',
    projectId: 'neuro-9dc86',
    authDomain: 'neuro-9dc86.firebaseapp.com',
    storageBucket: 'neuro-9dc86.firebasestorage.app',
    measurementId: 'G-MEJVS2WGMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPBte5hXqyQ7XpcuLWNU9pEspeGlRjTQ',
    appId: '1:199291967208:android:0ddf570617a5b283151b5d',
    messagingSenderId: '199291967208',
    projectId: 'neuro-9dc86',
    storageBucket: 'neuro-9dc86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLFZx3hU2QfA5Slc-YLKfprWqkdtBhzD0',
    appId: '1:199291967208:ios:4ece0e223f45e4d9151b5d',
    messagingSenderId: '199291967208',
    projectId: 'neuro-9dc86',
    storageBucket: 'neuro-9dc86.firebasestorage.app',
    iosBundleId: 'com.gerfalcon.example.offlineMenuTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLFZx3hU2QfA5Slc-YLKfprWqkdtBhzD0',
    appId: '1:199291967208:ios:2e69828e79db2b0e151b5d',
    messagingSenderId: '199291967208',
    projectId: 'neuro-9dc86',
    storageBucket: 'neuro-9dc86.firebasestorage.app',
    iosBundleId: 'it.arc.neuroNox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFnHyym94pRVpCPdcYc0MRnTBVA-bwN0',
    appId: '1:199291967208:web:a3a19ac86b246fbb151b5d',
    messagingSenderId: '199291967208',
    projectId: 'neuro-9dc86',
    authDomain: 'neuro-9dc86.firebaseapp.com',
    storageBucket: 'neuro-9dc86.firebasestorage.app',
    measurementId: 'G-YCYLDZL1NF',
  );
}
